
// XML_Token :: struct {
//     kind:       Kind;
//     text:       string;
//     location:   Source_Code_Location;
    
//     Kind :: enum #specified {
//         ERROR               :: -1;
//         EOF                 ::  0;
        
//         TAG_BEGIN           :: #char "<";
//         TAG_END             :: #char ">";
        
//         EQUALS              :: #char "=";
        
//         CLOSING_TAG_BEGIN   :: 255 + 1;
//         CLOSING_TAG_END     :: 255 + 2;
        
//         NAME                :: 255 + 3;
//     }
// }

